using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Alpha_m2_Converter
{
    public static class ressources
    {
        // from AnimationData.dbc
        public static Dictionary<string, int> AnimationDataWotlk = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
        {
            // some animations names from 0.5.3 that dn't exist in wrath, convert them
            { "Sit",  97}, // "SitGround", 97
            { "EatingStart", 122 }, // "EatingLoop"
            { "EatingEnd", 122 }, // "EatingLoop"
            { "PierceOff", 88 }, // "AttackOffPierce"
            {"Special2HL", 58 }, // Special2H
            {"Attack2HLPierce", 86 }, // Attack2HLoosePierce

            // dbc data
            {"Stand", 0 },
            {"Death", 1 },
            {"Spell", 2 },
            {"Stop", 3 },
            {"Walk", 4 },
            {"Run", 5 },
            {"Dead", 6 },
            {"Rise", 7 },
            {"StandWound", 8 },
            {"CombatWound", 9 },
            {"CombatCritical", 10 },
            {"ShuffleLeft", 11 },
            {"ShuffleRight", 12 },
            {"Walkbackwards", 13 },
            {"Stun", 14 },
            {"HandsClosed", 15 },
            {"AttackUnarmed", 16 },
            {"Attack1H", 17 },
            {"Attack2H", 18 },
            {"Attack2HL", 19 },
            {"ParryUnarmed", 20 },
            {"Parry1H", 21 },
            {"Parry2H", 22 },
            {"Parry2HL", 23 },
            {"ShieldBlock", 24 },
            {"ReadyUnarmed", 25 },
            {"Ready1H", 26 },
            {"Ready2H", 27 },
            {"Ready2HL", 28 },
            {"ReadyBow", 29 },
            {"Dodge", 30 },
            {"SpellPrecast", 31 },
            {"SpellCast", 32 },
            {"SpellCastArea", 33 },
            {"NPCWelcome", 34 },
            {"NPCGoodbye", 35 },
            {"Block", 36 },
            {"JumpStart", 37 },
            {"Jump", 38 },
            {"JumpEnd", 39 },
            {"Fall", 40 },
            {"SwimIdle", 41 },
            {"Swim", 42 },
            {"SwimLeft", 43 },
            {"SwimRight", 44 },
            {"SwimBackwards", 45 },
            {"AttackBow", 46 },
            {"FireBow", 47 },
            {"ReadyRifle", 48 },
            {"AttackRifle", 49 },
            {"Loot", 50 },
            {"ReadySpellDirected", 51 },
            {"ReadySpellOmni", 52 },
            {"SpellCastDirected", 53 },
            {"SpellCastOmni", 54 },
            {"BattleRoar", 55 },
            {"ReadyAbility", 56 },
            {"Special1H", 57 },
            {"Special2H", 58 },
            {"ShieldBash", 59 },
            {"EmoteTalk", 60 },
            {"EmoteEat", 61 },
            {"EmoteWork", 62 },
            {"EmoteUseStanding", 63 },
            {"EmoteTalkExclamation", 64 },
            {"EmoteTalkQuestion", 65 },
            {"EmoteBow", 66 },
            {"EmoteWave", 67 },
            {"EmoteCheer", 68 },
            {"EmoteDance", 69 },
            {"EmoteLaugh", 70 },
            {"EmoteSleep", 71 },
            {"EmoteSitGround", 72 },
            {"EmoteRude", 73 },
            {"EmoteRoar", 74 },
            {"EmoteKneel", 75 },
            {"EmoteKiss", 76 },
            {"EmoteCry", 77 },
            {"EmoteChicken", 78 },
            {"EmoteBeg", 79 },
            {"EmoteApplaud", 80 },
            {"EmoteShout", 81 },
            {"EmoteFlex", 82 },
            {"EmoteShy", 83 },
            {"EmotePoint", 84 },
            {"Attack1HPierce", 85 },
            {"Attack2HLoosePierce", 86 },
            {"AttackOff", 87 },
            {"AttackOffPierce", 88 },
            {"Sheath", 89 },
            {"HipSheath", 90 },
            {"Mount", 91 },
            {"RunRight", 92 },
            {"RunLeft", 93 },
            {"MountSpecial", 94 },
            {"Kick", 95 },
            {"SitGroundDown", 96 },
            {"SitGround", 97 },
            {"SitGroundUp", 98 },
            {"SleepDown", 99 },
            {"Sleep", 100 },
            {"SleepUp", 101 },
            {"SitChairLow", 102 },
            {"SitChairMed", 103 },
            {"SitChairHigh", 104 },
            {"LoadBow", 105 },
            {"LoadRifle", 106 },
            {"AttackThrown", 107 },
            {"ReadyThrown", 108 },
            {"HoldBow", 109 },
            {"HoldRifle", 110 },
            {"HoldThrown", 111 },
            {"LoadThrown", 112 },
            {"EmoteSalute", 113 },
            {"KneelStart", 114 },
            {"KneelLoop", 115 },
            {"KneelEnd", 116 },
            {"AttackUnarmedOff", 117 },
            {"SpecialUnarmed", 118 },
            {"StealthWalk", 119 },
            {"StealthStand", 120 },
            {"Knockdown", 121 },
            {"EatingLoop", 122 },
            {"UseStandingLoop", 123 },
            {"ChannelCastDirected", 124 },
            {"ChannelCastOmni", 125 },
            {"Whirlwind", 126 },
            {"Birth", 127 },
            {"UseStandingStart", 128 },
            {"UseStandingEnd", 129 },
            {"CreatureSpecial", 130 },
            {"Drown", 131 },
            {"Drowned", 132 },
            {"FishingCast", 133 },
            {"FishingLoop", 134 },
            {"Fly", 135 },
            {"EmoteWorkNoSheathe", 136 },
            {"EmoteStunNoSheathe", 137 },
            {"EmoteUseStandingNoSheathe", 138 },
            {"SpellSleepDown", 139 },
            {"SpellKneelStart", 140 },
            {"SpellKneelLoop", 141 },
            {"SpellKneelEnd", 142 },
            {"Sprint", 143 },
            {"InFlight", 144 },
            {"Spawn", 145 },
            {"Close", 146 },
            {"Closed", 147 },
            {"Open", 148 },
            {"Opened", 149 },
            {"Destroy", 150 },
            {"Destroyed", 151 },
            {"Rebuild", 152 },
            {"Custom0", 153 },
            {"Custom1", 154 },
            {"Custom2", 155 },
            {"Custom3", 156 },
            {"Despawn", 157 },
            {"Hold", 158 },
            {"Decay", 159 },
            {"BowPull", 160 },
            {"BowRelease", 161 },
            {"ShipStart", 162 },
            {"ShipMoving", 163 },
            {"ShipStop", 164 },
            {"GroupArrow", 165 },
            {"Arrow", 166 },
            {"CorpseArrow", 167 },
            {"GuideArrow", 168 },
            {"Sway", 169 },
            {"DruidCatPounce", 170 },
            {"DruidCatRip", 171 },
            {"DruidCatRake", 172 },
            {"DruidCatRavage", 173 },
            {"DruidCatClaw", 174 },
            {"DruidCatCower", 175 },
            {"DruidBearSwipe", 176 },
            {"DruidBearBite", 177 },
            {"DruidBearMaul", 178 },
            {"DruidBearBash", 179 },
            {"DragonTail", 180 },
            {"DragonStomp", 181 },
            {"DragonSpit", 182 },
            {"DragonSpitHover", 183 },
            {"DragonSpitFly", 184 },
            {"EmoteYes", 185 },
            {"EmoteNo", 186 },
            {"JumpLandRun", 187 },
            {"LootHold", 188 },
            {"LootUp", 189 },
            {"StandHigh", 190 },
            {"Impact", 191 },
            {"LiftOff", 192 },
            {"Hover", 193 },
            {"SuccubusEntice", 194 },
            {"EmoteTrain", 195 },
            {"EmoteDead", 196 },
            {"EmoteDanceOnce", 197 },
            {"Deflect", 198 },
            {"EmoteEatNoSheathe", 199 },
            {"Land", 200 },
            {"Submerge", 201 },
            {"Submerged", 202 },
            {"Cannibalize", 203 },
            {"ArrowBirth", 204 },
            {"GroupArrowBirth", 205 },
            {"CorpseArrowBirth", 206 },
            {"GuideArrowBirth", 207 },


        };

        public static Dictionary<string, int> MdxKeyboneNames = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
        {
            // those are the mdxbone.Name in alpha, completely which WOTLK keybone id they match since names are different.
            // commented those added in WOD or non keybones
            { "arm_L", 0}, // ArmL
            { "SpineLower", 4 }, // SpineLow

            { "Head", 6 }, // Head
            { "Jaw", 7 }, // Jaw
            { "thumb_L", 17 },
            { "thumb_R", 12 }, 
            // "finger_R"
            // "finger_L" // check
        };

        public static List<string> KnownMdxBoneNames = new List<string>()
        {
            "Hips",
            "LegBackL01",
            "LegBackL02",
            "FootBackL",
            "ToeBackL",
            "LegBackR01",
            "LegBackR02",
            "FootBackR",
            "ToeBackR",
            "Tail01",
            "Tail02",
            "SpineLower",
            "Belly",
            "SpineUpper",
            "Hump",
            "LegFrontL01",
            "LegFrontL02",
            "FootFrontL",
            "ToeFrontL",
            "LegFrontR01",
            "LegFrontR02",
            "FootFrontR",
            "ToeFrontR",
            "Neck",
            "Head",
            "Jaw",
            "SpineUp",
            "arm_L",
            "elbow_L",
            "hand_L",
            "finger_L",
            "thumb_L",
            "arm_R",
            "elbow_R",
            "hand_R",
            "finger_R",
            "fin",
            "-Blid_L01", // ??
            "-Flid_R01",
            "Blid_L",
            "Blid_R",
            "Flid_L",
            "Flid_R",
            "eye_L",
            "eye_R",
            "thumb_R",
            "hip_L",
            "knee_L",
            "ankle_L",
            "foot_L",
            "hip_R",
            "knee_R",
            "ankle_R",
            "foot_R",
        };
    }
}
